/**
 * Simple Echo API
 * Echo API for testing
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "DefaultApiImpl.h"

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

DefaultApiImpl::DefaultApiImpl(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : DefaultApi(rtr) {}

void DefaultApiImpl::echo_test_v1_ping_get(
    Pistache::Http::ResponseWriter& response) {
  response.headers().add<Pistache::Http::Header::AccessControlAllowOrigin>("*");
  response.headers().add<Pistache::Http::Header::ContentType>(
      MIME(Application, Json));
  nlohmann::json res;
  res["msg"] = "I'm alive";
  response.send(Pistache::Http::Code::Ok, res.dump());
}

}  // namespace api
}  // namespace server
}  // namespace openapitools
}  // namespace org
